### ISSUE TITLE
Deselecting annotations does not work

### ISSUE THREAD

**Issue by hmoenck** [BioroboticsLab/biotracker_core#108]
Deselecting an annotation does not work. I can only get rid of the selection by deleting the element.

**Comment by walachey** [comment]
It's not buggy, it's just not implemented. How'd it work? Just by clicking anywhere else? The event would probably have to be passed to other handlers regardless, right?

**Comment by hmoenck** [comment]
It seems pointless to be able to move it around and have it under your cursor before deleting it. Either remove it instantly when clicking it or add a deselect option. Maybe the escape key? Maybe this is something @jotpio can embed into his functions. He's implementing de-/selection of tracked entities.

**Comment by jotpio** [comment]
Will do!

**Comment by jotpio** [comment]
Done.
