### ISSUE TITLE
only one tracking rectangle per default

### ISSUE THREAD

**Issue by timlandgraf** [BioroboticsLab/biotracker_core#117]
a naive user would probably not know what the two rectangles are for. I assume one represents the tracking arena (all detections outside of it are disregarded) and one is the area that is used for rectifying the coordinates? but which is which?

First I would work with only one rectangle for both functionalities per default. If the user needs two different rects he/she may activate this in a settings tab.

**Comment by hmoenck** [comment]
No rectangles are used per default now. The whole frame is used for both.
They can be displayed using the menu.
