### ISSUE TITLE
number of tracked objects setting missing in background subtraction tracker

### ISSUE THREAD

**Issue by timlandgraf** [BioroboticsLab/biotracker_core#119]
where can I define the number of objects to be tracked?

**Comment by hmoenck** [comment]
The BST adds 2 points automatically. You can add / remove points via context menu.

**Comment by jotpio** [comment]
If you are paused while adding a new track, it is not processed immediately. So it is not showing up instantly.
For this case a visual indicator is planned.

**Comment by hmoenck** [comment]
Done. Shown instantly and displayed in the "view" tab
