### ISSUE TITLE
settings in side panel should update without additional button press

### ISSUE THREAD

**Issue by timlandgraf** [BioroboticsLab/biotracker_core#120]
it is such a PITA when you are searching for an optimal value but the program requires you to either press an update button or fwd the video

**Comment by hmoenck** [comment]
It's not a bug, it's a feature. I did this on purpose so you don't end up temporarily setting some nonsense. Like min blob size: 20 -[Backspace]-> 2 -[type 5]-> 25 <br>
The above example might crash your performance entirely if the image is noisy.

**Comment by hmoenck** [comment]
The "buttonless" version is now implemented. Including spinboxes!
