### ISSUE TITLE
NN2D Matching fragile

### ISSUE THREAD

**Issue by hmoenck** [BioroboticsLab/biotracker_core#130]
The identity function for poses seems extremely fragile and in practice causes id switches which are in no way sensible. [CODE HERE](https://github.com/BioroboticsLab/biotracker_core/blob/master/BioTracker/Plugin/BackgroundSubtraction/Model/TrackedComponents/pose/FishPose.cpp#L30)
I just took the code from the old fishtracker and put some comments about this issue in there ages ago.
![bad_match](https://user-images.githubusercontent.com/7859857/32383459-51ff76f8-c0b8-11e7-9040-65f19e44c9b5.jpg)
This is an example for a questionable id switch.

**Comment by walachey** [comment]
Yes, I wrote that solely hand-optimized for the old tracker.

But... one of the poses should have history information available. So maybe it's enough to estimate the distribution using the past X frames. That might fail when an entity suddenly accelerates, though.

**Comment by hmoenck** [comment]
46105cf2b7d8e34b7849749a3e39cad0cb54a5e4 provides an acceptable solution
