### ISSUE TITLE
Switching trackers causes crash

### ISSUE THREAD

**Issue by hmoenck** [BioroboticsLab/biotracker_core#133]
[*Relevant code*](https://github.com/BioroboticsLab/biotracker_core/blob/BioTracker3_publication/BioTracker/CoreApp/BioTracker/View/ComponentShape.cpp#L31). It seems like the tree datastructure is not unlinked correctly when unloading the previous plugin.

**Comment by jotpio** [comment]
is fixed by next commit in serialization branch
