### ISSUE TITLE
Polishing

### ISSUE THREAD

**Issue by hmoenck** [BioroboticsLab/biotracker_core#148]
Some polishing required:
1 LK: Initially trackpoints jump back
2 LK: More parameters should be exposed
3 BST: Initially has 2 points
4 BST: Rename "foreground" to something more meaningful
5 reset counter for entity numbers
6 View: Size and transparency of trackpoints
7 View: There is a renderbug near a trackpoint. Small circles randomly appear.
8 View: Changing numbers in the GUI should take effect immediately
9 View: checking Anti-Aliasing has no effect?
10 View: Size of "cursor position" label

**Comment by jotpio** [comment]
6View: transparency is done
8View: done
9View: is fixed
10View: fixed

**Comment by hmoenck** [comment]
Resolved to a satisfactory level
