### ISSUE TITLE
Crash on plugin reload

### ISSUE THREAD

**Issue by jotpio** [BioroboticsLab/biotracker_core#150]
One tracker is preloaded, load the second one then switch back to the first one. In my case it crashes then in the GraphicsView on removeGraphicsItem() while trying to remove the trackerview of the second tracker.

Second issue:
Loading the second tracker and then loading the first tracker again (via menu-->load tracker) causing a crash in the dataexportercsv on close()

**Comment by hmoenck** [comment]
@jotpio On which branch/commit did this occur?
Most recent to me is the publication branch af2c148b127127875d27e0a7e263f14c0aab4203 
That commit contains a couple of fixes, many of which are related to data exporters. 
There I couldn't reproduce any of those issues. I'm not sure whether I got the second one right: You have both trackers loaded (BT and LK, by lexicographic order BT is loaded "first"), select LK and do some tracking, then choose to load the DLL (or SO respectively) of BT and get a crash?

**Comment by jotpio** [comment]
Fixed in publication branch.
Was due to using unloaded plugin data, causing a segfault.
