### ISSUE TITLE
Videorecording doesn't work

### ISSUE THREAD

**Issue by xyl0copa** [BioroboticsLab/biotracker_core#162]
The recording while the tracking doesn't work properly...the recorded videos  are not even close to be usable.

**Comment by jotpio** [comment]
The BioTracker records the current view, so lags in the view are also in the video. You could track the data, then just visualize it without tracking and then record that. Nevertheless, we should think about a way to record a video without depending on the view.

**Comment by hmoenck** [comment]
Could you specify what doesn't work properly? How aren't they usable?

**Comment by hmoenck** [comment]
Ok, interesting. The frames are stored properly in the video, I could verify this by extracting them as single images. However, according to ffprobe the video was recorded at 1000fps (which I'm certain is a mistake of some sort), which leads to the video not being played properly, etc. 
We should check how the BioTracker determines at what fps to write the videos. Afaik it uses the framerate set to the camera (OCV default). 
Maybe you can try the following: When selecting the camera, explicitly put the resolution and fps. See also: https://github.com/BioroboticsLab/biotracker_core/wiki/02.-Tracking#cameras
maybe "whatever configuration it comes up at loading" was not sound to begin with?

**Comment by hmoenck** [comment]
@xyl0copa could you confirm that it works when setting the fps manually in the interface? Then this would boil down to a automatic fps detection problem.

**Comment by hmoenck** [comment]
@xyl0copa can the issue be closed?

**Comment by xyl0copa** [comment]
yes it's working. thanx
