### ISSUE TITLE
Framenumber

### ISSUE THREAD

**Issue by xyl0copa** [BioroboticsLab/biotracker_core#163]
It would be nice to not just have the current frame number but also the overall frame number next to it.
I think this would be useful und help while tracking.

**Comment by jotpio** [comment]
This is very simple to implement and will be included in my next commit.

**Comment by jotpio** [comment]
Added in the latest commit to the view+-branch. Is a total time also needed?
It would look like this: [00:00:10:145 / 01:23:22:349]. It would be quite cluttered and screen-filling.

**Comment by xyl0copa** [comment]
I think framenumber is enough.

**Comment by hmoenck** [comment]
Maybe this could be done on mousehover or near the scrollbar? Hovering might be very unintuitive...
