### ISSUE TITLE
zmq: unify track, paint and paintOverlay

### ISSUE THREAD

**Issue by justayak** [BioroboticsLab/biotracker_core#17]
The zmq client functions for paint, track and paintOverlay can be unified in one function to simplify the API. The tracking algorithm should "store" the paint results then and paint them when the appropriate events are called.

**Comment by timlandgraf** [comment]
Still we need two functions. One each time a new frame arrives and one for
update events.
Am 02.11.2015 6:10 nachm. schrieb "justayak" <notifications@github.com>:

**Comment by justayak** [comment]
After discussing with Tim we agreed that two functions (one for track, one for paint) are actually better. Otherwise, the tracker unnecessarily would need to deduct whether to track again or not, and, even worse, might need to send unnecessary matrices. So we will use only one paint function which does both, paint and paintOverlay and where the returned values define if a new texture must be rendered and/or the QPainter must be utilized. The track function is doing exactly that: track.
