### ISSUE TITLE
Does not run on Ubuntu 14.04

### ISSUE THREAD

**Issue by probonopd** [BioroboticsLab/biotracker_core#170]
The AppImage does not run on Ubuntu 14.04, a still-supported release of Ubuntu:

![](https://github.com/AppImage/appimage.github.io/blob/63e702f5bdcaf551cb28248e66c99b8b420754da/database/BioTracker/screenshot.png?raw=true)

Please see https://github.com/AppImage/AppImageKit/wiki/Creating-AppImages, especially https://github.com/AppImage/AppImageKit/wiki/Creating-AppImages#libstdcso6 for how to fix this.

Reference:
https://github.com/AppImage/appimage.github.io/pull/933

**Comment by MoritzMaxeiner** [comment]
> The AppImage does not run on Ubuntu 14.04, a still-supported release of Ubuntu:

Our CI/CD (which builds the AppImage) supports Ubuntu 18.04 (and Windows 10), so this is expected behavior (and it should've been documented when the AppImage was published).

**Comment by probonopd** [comment]
At this time, Ubuntu 16.04 is the oldest still-supported LTS version of Ubuntu, so I think it would be a good idea to target that one rather than the latest one. Would it be acceptable to build on Ubuntu 16.04 rather than Ubuntu 18.04?

**Comment by MoritzMaxeiner** [comment]
If you're referring to the aforementioned [CI/CD infrastructure](https://git.imp.fu-berlin.de/bioroboticslab/robofish/docker) I don't see a favorable ROI for the work of downgrading it.
If you're referring to an Ubuntu 16.04 based AppImage: Someone could build one manually for a biotracker release, but I'm not aware of any plans enabling that to come out of the CI/CD I linked to.

**Comment by MoritzMaxeiner** [comment]
I've updated the 3.2.1 release to make it clear the AppImage was built with Ubuntu 18.04.
