### ISSUE TITLE
AppImage crashes on startup

### ISSUE THREAD

**Issue by smidm** [BioroboticsLab/biotracker_core#171]
version 3.2.1 BioTracker-x86_64.AppImage on Fedora 28:
```
$ ./BioTracker-x86_64.AppImage

free(): invalid size
“./BioTracker-x86_64.AppImage” terminated by signal SIGABRT (Abort)
```
Fedora abbrt crash report (including stack trace, etc.):  http://cmp.felk.cvut.cz/~smidm/sklad/Biotracker_crash_report.zip

**Comment by MoritzMaxeiner** [comment]
Please try a recent image from the  [CI](https://git.imp.fu-berlin.de/bioroboticslab/biotracker/biotracker/pipelines), e.g. [this one](https://git.imp.fu-berlin.de/bioroboticslab/biotracker/biotracker/-/jobs/107747/artifacts/file/build/BioTracker-3.2.1-104-gb1dba5f1.AppImage).
