### ISSUE TITLE
Does not run on Ubuntu 16.04

### ISSUE THREAD

**Issue by probonopd** [BioroboticsLab/biotracker_core#172]
Follow-up from #170, the current version does not run on Ubuntu 16.04, a still-supported release of Ubuntu.

For AppImages, they are supposed to run on __all__ still-supported versions of Ubuntu, not just on the latest and greatest.

For a more detailed explanation, please see https://github.com/AppImage/AppImageKit/wiki/Creating-AppImages/cc2441518975caca23e9ce2dba6f08a22c678d1e#creating-appimages-that-are-compatible-with-many-systems.

Thanks for making an AppImage, and thanks for your consideration.

Reference:
https://github.com/AppImage/appimage.github.io/pull/933

**Comment by MoritzMaxeiner** [comment]
We've talked about this in https://github.com/BioroboticsLab/biotracker_core/issues/170, nothing has changed.
