### ISSUE TITLE
Port exisiting functionality from old codebase

### ISSUE THREAD

**Issue by nebw** [BioroboticsLab/biotracker_core#2]
There are a couple of things that have not been ported from the old codebase yet. When we started the refactoring, the old main GUI class BioTracker was replaced by a couple of smaller GUI components. There's still a couple of things from the old BioTracker class that should be ported to the new codebase.

see: https://github.com/BioroboticsLab/biotracker_core/blob/982f00430dfa70f838ebf6356f76c2198b79eea7/source/gui/BioTracker.cpp

Examples:
* Automatically restoring Tracker state when switching from one Tracker to another: BioTracker::trackingAlgChanged(Algorithms::Type trackingAlg)
* Serialization and file hash calculation: BioTracker::storeTrackingData(const std::string &filename)
* Saving of window geometry and state when closing the application: BioTracker::closeEvent(QCloseEvent* event)
* Forwarding of keyboard/mouse events to TrackingAlgorithm: BioTracker::event(QEvent *event)

**Comment by justayak** [comment]
Still missing:
* Geometry config
* State config
when closing the Application

**Comment by justayak** [comment]
too broad
