### ISSUE TITLE
remove Boost headers download

### ISSUE THREAD

**Issue by berleon** [BioroboticsLab/biotracker_core#22]
Biotracker only builds with the boost 1.57  headers. This is  due to a regression in the boost serialization introduced in version 1.58 [[ticket]](https://svn.boost.org/trac/boost/ticket/11245)[[stackoverflow]](http://stackoverflow.com/questions/29880853/boost-serialization-with-private-constructor-works-in-1-57-not-in-1-58). To build on systems with a boost version higher then 1.57 we download the 1.57 boost headers, compile against them and then link against the possible different boost system library.
It would be better to simple fix our code so it works also with the newer boost versions and remove the cpm_boost module.

**Comment by TobiasLudwig** [comment]
> compile against them and then link against the possible different boost system library
Don't do that! This can lead to random crashes :(

**Comment by justayak** [comment]
What is the status of this ticket?

**Comment by nebw** [comment]
The dependency has been removed in f7166523a8ebfd86be1f7ba7aebeaf6f891bc86d. The issue affects only boost::serialization, which is not used in biotracker_core.
