### ISSUE TITLE
Documentation: Explain how to install BioTracker

### ISSUE THREAD

**Issue by justayak** [BioroboticsLab/biotracker_core#24]
We should write an explanation of how to build/install the BioTracker. I already started with the wiki page:

https://github.com/BioroboticsLab/biotracker_core/wiki/dev_build

**Comment by hmoenck** [comment]
I'll simply add this to the readme. Read to use builds should go to the github releases page.

**Comment by hmoenck** [comment]
Will be part of the next merge to the master branch
