### ISSUE TITLE
Qt5 static compilation

### ISSUE THREAD

**Issue by justayak** [BioroboticsLab/biotracker_core#26]
As we link boost statically now because of issue #25 we might think about linking Qt statically as well. We should consider this for example.. http://stackoverflow.com/questions/17259277/cmake-static-link-qt5

**Comment by nebw** [comment]
https://cmake.org/cmake/help/v2.8.8/cmake.html#prop_tgt:LINK_SEARCH_END_STATIC

**Comment by nebw** [comment]
Will be handled by package management under Linux and required DLLs should be bundled on Windows / OSX
