### ISSUE TITLE
Remove predef

### ISSUE THREAD

**Issue by justayak** [BioroboticsLab/biotracker_core#40]
stay compatible with ubuntu linux boost libs

**Comment by nebw** [comment]
Did you figure out why this header is not contained in the ubuntu packages? Seems weird...

**Comment by justayak** [comment]
Didn't had the time to further investigate this issue but as we only used functionalities that are provided by the compiler in question (msvc) as default I felt it did not hurt to change it back. I think @Sh4kE did more research on that issue though..
