### ISSUE TITLE
Multiple copies of the Grid3D class

### ISSUE THREAD

**Issue by berleon** [BioroboticsLab/biotracker_core#42]
The Grid3D Class needs the biotracker and the pipeline. 
As the biotracker and the pipeline are two independent modules, it cannot belong to either of them. 
This has lead to the strange situation, that every package that needs the Grid3D class, has its own
copy.

A list of all Grid3D class copies:

* https://github.com/berleon/pybeesgrid/blob/master/src/Grid3D.h
* https://github.com/BioroboticsLab/parameteroptimization/blob/master/parameteroptimization/Grid3D.h
* https://github.com/BioroboticsLab/groundtruthConvert/blob/master/groundtruthConvert/Grid3D.h
* There should also be a copy in the ground truth creation module.

There are twp possible fixes:

1. create a new repository for the `Grid3D` class and use it in all above listed projects.
1. as the `Grid3D` class is only legacy code, try to remove it and only use the `PipelineGrid` class.
 This would change the GT file format and therefore all existing GT files must be converted. It is 
 not clear to me, if the `PipelineGrid` could replace the `Grid3D` to 100 percent.

**Comment by berleon** [comment]
@nebw @hmoenck

**Comment by hmoenck** [comment]
Creating a repository for only one class seems overkill, though it looks like the most safe thing to do. Are there any more common datastructures and functionalities which can be offloaded into one repository for common use? Json settings are the first thing which come to my mind. The settings class appears in many very similar variations in many repositories.

**Comment by justayak** [comment]
What about embedding it into biotracker_core? Than one only needs to link against the core and can choose what tools to use.. that way we can also provide trackers with the tools. Downside is that the core might get too bloated if we dont take care

**Comment by nebw** [comment]
biotracker_core should not include any BeesBook-relevant code. My preferred solution would be to only include the Grid3D class in the groundtruthConvert repo. Seems like this the best place to store legacy code. The groundtruthConvert should have a function to automatically convert Grid3Ds to PipelineGrids as well.

**Comment by hmoenck** [comment]
The groundtruthConverter seems to be the best place, I agree. It has very few dependencies and few object files to compile. This shouldn't increase to much in the future, so it is a rather lightweight dependency itself. 
About the converter function we've been talking. I basically did this in a local project, so I can add this later.
