### ISSUE TITLE
Render bugs when drawing text with QPainter

### ISSUE THREAD

**Issue by nebw** [BioroboticsLab/biotracker_core#48]
![text_render](https://cloud.githubusercontent.com/assets/378878/11742047/38582462-9ffd-11e5-894c-a21da2da5841.png)

**Comment by justayak** [comment]
From @nebw 
> Have you determined the cause of BioroboticsLab/biotracker_core#48?

**Comment by justayak** [comment]
QPainter expects the Opengl context to be in a particular set of states and I believe that our current, handwritten Opengl somehow messes around with that. I suspect, that the QGLWidget was handling stuff differently than the new QOpenGLWidget as well but all of this is just a hunch! However, to prevent pocking around in the dark I started a branch (opengl_rewrite) that tries to simplify that issue as much as possible (by mostly rely on qt functions only) and hopefully fixes all our graphic related issues at the same time.

**Comment by justayak** [comment]
fixed with #52
