### ISSUE TITLE
Screenshot function

### ISSUE THREAD

**Issue by justayak** [BioroboticsLab/biotracker_core#50]
to be implemented

**Comment by nebw** [comment]
see https://github.com/BioroboticsLab/biotracker_gui/commit/c5148417d17b040079c4327022d6ef3751b42288

**Comment by Sh4kE** [comment]
unfortunatly jenkins does not build anymore, see:

http://willi.imp.fu-berlin.de/job/Build%20Biotracker%20Ubuntu/51/console

**Comment by nebw** [comment]
fixed in https://github.com/BioroboticsLab/biotracker_gui/commit/7bb1866775a61c99a5cf542c9ff62b7053904371
