### ISSUE TITLE
Weird screen bug with videos with sound

### ISSUE THREAD

**Issue by justayak** [BioroboticsLab/biotracker_core#53]
This is a very strange bug and I am not sure what exactly is going on yet: When I replay a video with stereo sound I get a distorted screen: 
![image](https://cloud.githubusercontent.com/assets/831215/11918598/62c03644-a738-11e5-9149-96c01b546b9c.png)

.. but when the same video with surround sound is loaded everything is fine:
![image](https://cloud.githubusercontent.com/assets/831215/11918604/8fc8cd68-a738-11e5-8966-93a7efd3aa7c.png)

Some further investigation is needed

**Comment by justayak** [comment]
oups, closed it by accident..

**Comment by timlandgraf** [comment]
This is a opencv bug that some codecs produce. The image matrix returned by
the read operation has erroneous values in one or two member variables. We
were able to fix it manually but it should best be fixed within opencv.
Am 20.12.2015 4:42 nachm. schrieb "Julian Tanke" <notifications@github.com>:

**Comment by justayak** [comment]
Still exists within Opencv3

**Comment by nebw** [comment]
Fixed in  afad2cb2ada9f3743cfd24f11b7f54912a68ba80
