### ISSUE TITLE
Upgrade to OpenCV 3

### ISSUE THREAD

**Issue by justayak** [BioroboticsLab/biotracker_core#56]
Tbd if there is no reason against OpenCV 3

**Comment by nebw** [comment]
Is it possible to support both version 2 and 3. Afaik no distribution ships OpenCV 3 yet. But I'm generally in favour of always keeping up to date with upstream packages.

**Comment by justayak** [comment]
I switched to OpenCV 3 and the Biotracker "almost" compiles: the problem line is:

```cpp
void ImagePreProcessor::init() {
    // the following line does not compile..
    _pMOG = std::make_unique<cv::BackgroundSubtractorMOG2>(
                _settings.getValueOfParam<int>(PREPROCESSORPARAM::BG_MOG2_HISTORY),
                _settings.getValueOfParam<float>(PREPROCESSORPARAM::BG_MOG2_VAR_THRESHOLD),
                _settings.getValueOfParam<bool>(PREPROCESSORPARAM::BG_MOG2_SHADOW_DETECTION));
}
```

in CORE: biotracker/util/imagePreProcessor/ImagePreProcessor
Error:
```
/usr/include/c++/5/bits/unique_ptr.h:765: error: invalid new-expression of abstract class type 'cv::BackgroundSubtractorMOG2'
     { return unique_ptr<_Tp>(new _Tp(std::forward<_Args>(__args)...)); }
                                                                     ^
```

When commenting the problematic line the tracker compiles without a problem.

@nebw What do you mean with supporting both versions? That the very same BioTracker-app can load both trackers written with OpenCV2 as well as OpenCV3?

**Comment by nebw** [comment]
After a in-person discussion we decided to only support OpenCV3 from now on.

**Comment by nebw** [comment]
Remaining PreProcessor issues will be discussed in #58
