### ISSUE TITLE
Add numpy to CMakeList

### ISSUE THREAD

**Issue by justayak** [BioroboticsLab/biotracker_core#6]
add the moment numpy gets included without the help of cmake. We need to change that asap

**Comment by berleon** [comment]
checkout the [CheckIncludeFiles](https://cmake.org/cmake/help/v3.0/module/CheckIncludeFiles.html). Somethink like `CheckIncludeFiles("numpy/ndarraytypes.h" HAVE_NUMPY)` should to the job.

**Comment by justayak** [comment]
not relevant anymore thanks to zmq
