### ISSUE TITLE
tracking "mechanics"

### ISSUE THREAD

**Issue by timlandgraf** [BioroboticsLab/biotracker_core#73]
objects can't be tracked perfectly, the tracker 
- loses track due to occlusions or whatver reason
- might find wrong correspondences (jumps on a different, nearby object)
- determines slightly wrong object parameters (orientation might be off a bit)

hence, the user needs to interact with the results on screen. I suggest the framework can provide a rudimentary set of interaction sets and datastructures that help representing the state of objects. needs to be discussed and planned thoroughly.

**Comment by nebw** [comment]
A very rudimentary version of this is already implemented in the object model thats also used for serialization purposes: https://github.com/BioroboticsLab/biotracker_core/blob/master/biotracker/serialization/TrackedObject.h

**Comment by justayak** [comment]
Why cant this be handled with the current implementation? The Tracker knows in what view it is, where the mouse is, if the mouse is clicked, if the screen is panned, zoomed etc.
Or is the plan to create a more general function for this?

**Comment by hmoenck** [comment]
More general functions have been created in BT3. Moving, rotating, ....
