### ISSUE TITLE
video time stamp

### ISSUE THREAD

**Issue by timlandgraf** [BioroboticsLab/biotracker_core#74]
the frame position should be displayed using a timestamp (e.g. when clicking on the frame number, the display should switch)

**Comment by justayak** [comment]
Just to clarify: by time stamp you mean: _native video fps_ * _frame number_ where the origin (0) is the beginning of the video, correct?
How should this behave when given a stream of images (that might be independent of each other) and how should this behave in case the computer camera is used?

**Comment by hmoenck** [comment]
Done in view+ branch
