### ISSUE TITLE
Fps calculation is wrong

### ISSUE THREAD

**Issue by justayak** [BioroboticsLab/biotracker_core#78]
The current fps calculation is wrong

**Comment by h2nguyen** [comment]
I have proposal to resolve this problem.

Using updated fps average mean frame by frame:

```
currentFps = (lastFpsMean * (frameNumber - 1.0) + lastFps) / frameNumber ;
```

**Comment by justayak** [comment]
@h2nguyen thanks for the idea, however, I believe this is not the way how the fps calculation should work in this particular place (though I might actually be wrong) as we want to be exact in each frame (so we can easier debug a tracker etc.).
The ticket description is way too vague so I will try  to give some context:

The current fps-calculation does not calculate the total elapsed time that the program takes to show the next frame on-screen. Instead, it tracks how long it takes to solely track.. I will try to make this more clear with an image:

![fps_calc](https://cloud.githubusercontent.com/assets/831215/13436809/49fd7e0a-dfe1-11e5-9e44-3d79051c70d5.png)

At the moment, we only use timeframe __A__ to calculate our fps while the totally elapsed time also contains timeframe __B__. We now need to first figure out what exactly we want as all versions (only __A__ vs __A__ + __B__ vs some interpolation like suggested by @h2nguyen) make sense somehow.. however I would suggest to change the name when we only factor __A__ into the calculation (maybe: __tracking time__ or something similar)

**Comment by timlandgraf** [comment]
I'm not sure if we really want accuracy in the GUI. The frame rate display
would jump up and down every frame if we would implement an exact update.
The user probably just wants an approximate measure, or should insert code
to measure precise timings.

The runtime of the tracking module can be measured inside the module.
Module time plus display time should be displayed as frame rate.

What do the others think?
Am 01.03.2016 19:34 schrieb "Julian Tanke" <notifications@github.com>:
