### ISSUE TITLE
add ".mov" to filetype filter 

### ISSUE THREAD

**Issue by timlandgraf** [BioroboticsLab/biotracker_core#84]
i have a video in the MOV container, encoded with mpeg4 which opens just fine after renaming its suffix. please add "mov" to the filter list of the open file dialog.

add the "all files" option too to be nice to new container names

**Comment by justayak** [comment]
BioroboticsLab/biotracker_gui@bc3a8a00846965314e23b7a9c3859ce28e558e0e
