### ISSUE TITLE
frozen video and black screen

### ISSUE THREAD

**Issue by justayak** [BioroboticsLab/biotracker_core#85]
Moved from: https://github.com/BioroboticsLab/biotracker_lucasKanade/issues/10#issuecomment-203447202

Commited by: @timlandgraf 
"I encounter a weird bug that is often happening when i leave the tracker for like a minute or so.

note that I am running the tracker in a virtualbox

when I return from windows to the tracker and advance the video one frame the next frame is displayed correctly, the tracker finds a correct position, but then, for all following frames, nothing happens, the video is frozen.

when I click the play button the video area becomes black, the video control buttons switch to pause instead of play, etc, but the slider doesnt move. GUI is still responsive but no graphics content is displayed

when reloading the video, the tracker correctly displays previously found positions and everything works fine.

I tested moving the focus from VM window to some my browser in windows, wait for a short time and go back to the VM.

30 seconds: freezes (tested 2 times)
25 seconds: freezes (tested 4 times)
20 seconds: still works (tested 3 times)
15 seconds: stll works (tested 2 times)

all tests were consistent.

any idea?"

"it even happens when leaving the mouse on the biotracker GUI for like 30 s, no switching between systems"

"happens in fullscreen mode alike"

"I tested it again WITHOUT any tracker selected and I get the same behavior. Thus it is not related to the tracker and this ticket should be moved to the core or gui component."

**Comment by justayak** [comment]
I managed to reproduce the issue in my VM (Ubuntu 15.10, x64) but not on my native system.

**Comment by justayak** [comment]
This seems to be a problem with the VideoCapture object inside of a virtual machine. I could reproduce the issue with following code:
```cpp
#include <cv.h>
#include <highgui.h>
#include <opencv2/core/core.hpp> 
#include <opencv2/videoio/videoio.hpp>
#include <opencv2/highgui/highgui.hpp>
#include <string>
#include <iostream>

using namespace cv;
using namespace std;

int main(){
	
	const string ref = "/home/biotracker/Downloads/MVI_7555.MOV";

	cv::VideoCapture capt(ref);	
	Mat im;
	capt >> im;

	for (int i = 0; i < 10; i++) {
		cout << "im empty: " << im.empty() << endl;		
		imshow("qq", im);
		char c = waitKey(60000);
		cout << "time is over, nextframe" << endl;
		capt >> im;
	}
	

	return 0;
}
```

This error does not occur when I use my native system or docker

**Comment by justayak** [comment]
This seems to be a codec issue.. converting the failing video from .mov to .avi "fixed" the issue for now. But further investigation should be committed to this bug

**Comment by nebw** [comment]
@justayak This seems like something that should be reported to the OpenCV developers. Shouldn't be too much effort either since you already have a reproducible test case.

**Comment by timlandgraf** [comment]
@justayak which codec did you convert the video to? just changing the container (from .mov to .avi) doesn't resolve the problem for me.

If I remember correctly, opencv  calls ffmpeg and ffmpeg directly calls the codec which should deliver the frame. the error could happen on either of the three sides. We should thoroughly debug at least the opencv code to look deeper into why that happens.

**Comment by timlandgraf** [comment]
@justayak I could reproduce the bug on a native linux.

**Comment by justayak** [comment]
@timlandgraf Ubuntu 15.10?

**Comment by timlandgraf** [comment]
@justayak 15.04

**Comment by timlandgraf** [comment]
I compiled opencv without ffmpeg but with gstreamer and I could open some videos (also those that I used when experiencing the bug) and these played fine.

Then I compiled opencv with ffmpeg and there it was again: the black screen (same video)

**Comment by justayak** [comment]
I opened a ticket for OpenCV: https://github.com/Itseez/opencv/issues/6356

**Comment by justayak** [comment]
This issue was resolved in OpenCV
