### ISSUE TITLE
screening of video filetypes

### ISSUE THREAD

**Issue by timlandgraf** [BioroboticsLab/biotracker_core#86]
before going public we should test whether various common video codecs and container formats can be opened properly. 

the whole lab could take part, provide random video files and test them with the deployed binary package.

**Comment by hmoenck** [comment]
Yup. Moreover I discovered strange errors may occur on different machines, namely David B.'s notebook. The video loading is done by the VideoReader class, which is mostly tied to the system codecs. The ffmpeg library shipped with OCV doesn't seem to come with too many codecs of its own. So you might want to install a codec pack?
