### ISSUE TITLE
Provide the trackers with the currently used filename

### ISSUE THREAD

**Issue by justayak** [BioroboticsLab/biotracker_core#89]
E.g. the currently running video. However, how should this behave when the camera is used and how should this behave when a set of images is loaded? This question came up when handling with following ticket: https://github.com/BioroboticsLab/biotracker_lucasKanade/issues/14

**Comment by nebw** [comment]
One option would be: Don't return a string, but rather a vector\<string\> (would be empty in case of camera) or even an boost::optional\<vector\<string\>\> (that is invalid if camera input is used). 

Another option: Always return a string. In the case of multiple images return something like "{FirstImage}.png...{LastImage}.png" and in the case of camera input maybe "CameraInput{TimeStamp}".

**Comment by justayak** [comment]
How about providing an event "onFileChanged"? This will be called once when a video is opened (as the video file is only opened "once", but all the time when a set of images is called (as each image stands for itself) while, when a camera is used, the event will never occur.

**Comment by nebw** [comment]
Sounds good to me. But the event should also be called initially when a new tracker is loaded (i.e. even when the image/video has been opened before loading the tracker).
