### ISSUE TITLE
Enable/Disable tracking

### ISSUE THREAD

**Issue by justayak** [BioroboticsLab/biotracker_core#90]
We should enable the BioTracker to let the user enable/disable tracking. That means: the user can still play the video etc. and the previously tracked elements will be shown as expected but the actual tracking algorithms (**TrackingAlgorithm::track**) will not be called. We need to change the **TrackingAlgorithm::paint** and the **TrackingAlgorithm::paintOverlay** function (add the current frame number to their function definition). 

**This will break all tracker modules so we need to adapt them as well**

**Comment by timlandgraf** [comment]
Semi-nice solution would be a default keyboard shortcut implemented on the tracker level. The track function that individual trackers would override would be called from another funcrion, defined in the base class. In this one we would implement the switch.

**Comment by justayak** [comment]
Actually, I think it is a good idea to put this functionality in the tracker rather than in the **TrackingThread** from an OOP-point-of-view. The TrackingThread then simply has to call **TrackingAlgorithm::setTracking(bool)**, the rest will be handled inside the (abstract) tracking class. This is transparent to both other trackers as well as the BioTracker internals. We would then need some sort of API call towards the **BioTracker** facade to enable the guy to modify this value

**Comment by hmoenck** [comment]
This is implemented in the Biotracker3, yet needs some testing for the release. However the tracker has to deal with the issue of frame numbers by itself. There is no guarantee for the tracker to be called with ascending framenumbers or similar.
